on: [push, pull_request]
name: Lint
jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: OSKAR-PHP-CS-Fixer
      uses: OskarStark/php-cs-fixer-ga@3.8.0
      with:
        args: --diff --dry-run
